### PR TITLE
Add User-Agent and Accept headers

### PR DESCRIPTION
**Pull request by williamdes**
Same request as https://github.com/anson-vandoren/mailfeed/pull/6

Fixes: `https://www.reddit.com/r/rust/.rss: 403 Forbidden`: `2023-11-26T10:47:13.103Z ERROR [paperboy::rss] Error while loading feed https://www.reddit.com/r/rust/.rss: unable to parse feed: no root element`

### CODE REVIEW

**Comment by eduardostuart** [comment]
Hi @williamdes ,
Just tested it on Reddit and it worked. 
Thank you for the fix!

**Comment by williamdes** [comment]
> Hi @williamdes , Just tested it on Reddit and it worked. Thank you for the fix!

Thank you too for the quick merge
I might do some more changes

**Comment by williamdes** [comment]
Could you provide non musl binaries ?

**Comment by eduardostuart** [comment]
You can find other binaries on the releases page.  https://github.com/eduardostuart/paperboy/releases/tag/v0.1.8 
I'm only creating for musl and [apple-darwin](https://github.com/eduardostuart/paperboy/blob/main/.github/workflows/release.yml#L19)

I'll create a new release later today including your fix.

**Comment by williamdes** [comment]
If I port the subject in ENV feature like in https://github.com/anson-vandoren/mailfeed/pull/5/files

And provide a way to send an email for each feed would you accept it?

**Comment by eduardostuart** [comment]
About the subject, yes - that's ok. 

About the email for each feed, I'm not sure if I understand that. What do you mean?

**Pull request merged**
