### PR TITLE
Implement subject variable in the mailer

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by williamdes** [comment]
I think it is best to do in another PR the feature to send all in once or an email by feed
And in that PR to implement variables in the subject like https://github.com/anson-vandoren/mailfeed/pull/5

**Comment by williamdes** [comment]
Screenshot_2023-11-26-14-23-23-543_com microsoft office outlook

I would like to have one email by feed rather than a summary of them like the screenshot shows using the other tool

**Comment by eduardostuart** [comment]
If you want to implement a separate command on the CLI for individual feeds, I'm okay with that. However, I have no plans to change the current "deliver" command. I believe sending individual emails per feed somewhat contradicts the purpose of the tool. My proposal would be an option on the "deliver" cmd to send emails individually or a different command for that.

**Comment by williamdes** [comment]
> My proposal would be an (optional) option on the "deliver" cmd to send emails individually or a different command for that.

Sounds like a good option

> I believe sending individual emails per feed somewhat contradicts the purpose of the tool.

I can understand that

I could create a file for each feed and trigger the command for each file
This would do the same feature 🤔

**Pull request merged**
